codecov:
  branch: main
  notify:
    require_ci_to_pass: no

  coverage:
    range: 70..100
    round: down
    precision: 2
    status:
      project:
        default:
          target: 75%
          threshold: 10%

      patch:
        default:
          target: 60%
          threshold: 10%

      changes: no

  parsers:
    gcov:
      branch_detection:
  conditional: yes
  loop: yes
  method: no
  macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
