language: dart
dart:
  - stable

branches:
  only:
    - master

jobs:
  include:
    - stage: Test
      name: Static Analysis
      env: MAKETARGET=analyze
    - name: Unit Test
      env: MAKETARGET=unit-test
    - name: Coverage Report
      env: MAKETARGET=coverage
script:
  - make $MAKETARGET

after_success:
  - bash <(curl -s https://codecov.io/bash)
