name: model_mixer
version: 0.1.0
description: Model Mixer is a library to automate model generation for automated tests.
repository: https://github.com/HelloCuriosity/model-mixer
issue_tracker: https://github.com/HelloCuriosity/model-mixer/issues

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  lipsum: ^1.0.1

dev_dependencies:
  test: ^1.14.3
  test_cov: ^0.2.1
