name: modelmixer
description: A new Flutter package.
version: 0.0.1
author:
homepage: https://github.com/HelloCuriosity/model-mixer

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  lipsum: ^1.0.1

dev_dependencies:
  test: ^1.14.3
