name: Model Mixer
description: Model Mixer is a library to automate model generation for automated tests.
version: 0.0.1
author: Hello Curiosity
homepage: https://github.com/HelloCuriosity/model-mixer

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  lipsum: ^1.0.1

dev_dependencies:
  test: ^1.14.3
