name: Model Mixer 🍹

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cancel-previous:
    name: Cancel Previous
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Build
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    needs: cancel-previous
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Static Analysis
        run: dartanalyzer --fatal-warnings lib
      - name: Unit Test
        run: pub run test
      - name: Coverage
        run: pub run test_cov
      - name: Report
        uses: codecov/codecov-action@v1.2.1
        with:
          fail_ci_if_error: true
